// 献立レシピDB
// すべて「料理研究家リュウジのバズレシピ.com」の実在レシピを参照（URL・材料・手順は実際のページから取得して検証済み）。
// baseServings = 何人前を基準に材料を記載しているか（分量スケール計算に使用）。
// 条件対応: 安い素材 / 手間少なめ / 洋・中華中心 / 濃い味 / ほたて・いか・チンゲンサイ・きのこ 不使用。

const RECIPES = [
  // ================= 主菜 =================
  {
    id: "buta-suisho",
    title: "豚こまの水晶漬け",
    type: "main",            // main=主菜 / side=副菜
    ingredientTags: ["豚こま"],
    time: "約20分（漬け込み時間は除く）",
    genre: "中華風・さっぱり濃い味",
    blurb: "100g100円前後の豚こまが主役。茹でてタレに漬けるだけ。作り置き＆大量調理に強い。",
    url: "https://bazurecipe.com/2022/08/07/%E8%B1%9A%E3%81%93%E3%81%BE%E3%81%AE%E6%B0%B4%E6%99%B6%E6%BC%AC%E3%81%91/",
    baseServings: 2,
    ing: [
      { name: "豚こま肉", qty: 320, unit: "g" },
      { name: "酒", qty: 1.5, unit: "大さじ" },
      { name: "片栗粉", qty: 4, unit: "小さじ" },
      { name: "みょうが", qty: 3, unit: "個" },
      { name: "生姜", qty: 10, unit: "g" },
      { name: "醤油", qty: 3, unit: "大さじ" },
      { name: "酢", qty: 3, unit: "大さじ" },
      { name: "砂糖", qty: 2, unit: "大さじ" },
      { name: "水", qty: 1, unit: "大さじ" },
      { name: "ごま油", qty: 1, unit: "大さじ" },
    ],
    fixed: [
      { name: "塩コショウ", text: "適量" },
      { name: "味の素", text: "適量（お好みで）" },
      { name: "輪切り唐辛子（鷹の爪）", text: "適量" },
    ],
    steps: [
      "豚こま肉に酒・塩コショウ・片栗粉をもみこむ。",
      "沸騰したお湯でサッと茹でる。",
      "ザルにあけて流水で冷やし、よく絞る。",
      "みょうが・生姜・醤油・酢・砂糖・水・味の素・ごま油・鷹の爪を混ぜてタレを作る。",
      "肉にタレを絡めて、冷やしたら完成。",
    ],
  },
  {
    id: "yamitsuki-tori",
    title: "やみつき鶏",
    type: "main",
    ingredientTags: ["鶏もも"],
    time: "約15分",
    genre: "洋風・こってり濃い味",
    blurb: "ケチャップ×バター×タバスコの背徳ダレ。ご飯がすすむ高校生ウケ抜群の味。",
    url: "https://bazurecipe.com/2021/10/21/%E3%82%84%E3%81%BF%E3%81%A4%E3%81%8D%E9%B6%8F/",
    baseServings: 2,
    ing: [
      { name: "鶏もも肉", qty: 320, unit: "g" },
      { name: "片栗粉", qty: 1.5, unit: "大さじ" },
      { name: "バター", qty: 15, unit: "g" },
      { name: "砂糖", qty: 1, unit: "大さじ" },
      { name: "ケチャップ", qty: 1, unit: "大さじ" },
      { name: "しょうゆ", qty: 1, unit: "大さじ" },
      { name: "酒", qty: 1, unit: "大さじ" },
      { name: "にんにく", qty: 1, unit: "かけ" },
    ],
    fixed: [
      { name: "塩コショウ", text: "適量" },
      { name: "味の素", text: "適量（お好みで）" },
      { name: "タバスコ", text: "適量（お好みで）" },
      { name: "黒コショウ・マヨネーズ", text: "お好みで" },
    ],
    steps: [
      "鶏もも肉に塩コショウと片栗粉をまぶす。",
      "バターで焼く。",
      "ケチャップ・醤油・酒・砂糖・おろしにんにく・味の素・タバスコを混ぜたタレを入れる。",
      "タレを絡める。",
      "黒胡椒をふって完成。",
    ],
  },
  {
    id: "mune-tamasu",
    title: "茹で鶏むねの玉酢漬け",
    type: "main",
    ingredientTags: ["鶏むね"],
    time: "約15分（漬け込み時間は除く）",
    genre: "中華風・さっぱり濃い味",
    blurb: "むね肉を1分茹でて漬けるだけ。安い・ヘルシー・大量に作りやすい漬け込み系。",
    url: "https://bazurecipe.com/2024/02/27/%E9%B6%8F%E3%82%80%E3%81%AD%E8%82%89%E3%81%AE%E7%8E%89%E3%81%AD%E3%81%8E%E6%BC%AC%E3%81%91/",
    baseServings: 2,
    ing: [
      { name: "鶏むね肉", qty: 350, unit: "g" },
      { name: "玉ねぎ", qty: 120, unit: "g" },
      { name: "塩", qty: 0.33, unit: "小さじ" },
      { name: "片栗粉", qty: 4, unit: "小さじ" },
      { name: "酒", qty: 4, unit: "小さじ" },
      { name: "醤油", qty: 3, unit: "大さじ" },
      { name: "砂糖", qty: 1.5, unit: "大さじ" },
      { name: "酢", qty: 1.5, unit: "大さじ" },
      { name: "ごま油", qty: 1, unit: "大さじ" },
    ],
    fixed: [
      { name: "味の素", text: "適量（お好みで）" },
      { name: "輪切り唐辛子", text: "適量" },
    ],
    steps: [
      "玉ねぎをみじん切りにして水にさらす。",
      "鶏むね肉に塩・片栗粉・酒を混ぜ、お湯で1分茹でる。",
      "水を切った玉ねぎに醤油・砂糖・酢・味の素・ごま油・鷹の爪を混ぜてタレを作る。",
      "茹でた鶏むね肉をタレに漬けて完成。",
    ],
  },
  {
    id: "shiko-tacorice",
    title: "至高のタコライス",
    type: "main",
    ingredientTags: ["ひき肉"],
    time: "約25分",
    genre: "洋風（メキシカン）・スパイシー濃い味",
    blurb: "スパイスの効いたタコミートを大鍋で。ご飯にのせるだけで15人分もラク。",
    note: "参考レシピは合いびき肉ですが、牛肉を避けたい場合は豚ひき肉だけでも美味しく作れます（材料は豚ひきで記載）。",
    url: "https://bazurecipe.com/2022/06/03/%E8%87%B3%E9%AB%98%E3%81%AE%E3%82%BF%E3%82%B3%E3%83%A9%E3%82%A4%E3%82%B9/",
    baseServings: 2,
    ing: [
      { name: "豚ひき肉", qty: 100, unit: "g" },
      { name: "玉ねぎ", qty: 90, unit: "g" },
      { name: "にんにく", qty: 3, unit: "片" },
      { name: "ホールトマト缶", qty: 0.5, unit: "缶" },
      { name: "サラダ油", qty: 2, unit: "大さじ" },
      { name: "コンソメ", qty: 1.5, unit: "小さじ" },
      { name: "ケチャップ", qty: 1, unit: "大さじ" },
      { name: "ウスターソース", qty: 1, unit: "小さじ" },
      { name: "チリパウダー", qty: 0.66, unit: "小さじ" },
      { name: "オレガノ", qty: 0.5, unit: "小さじ" },
      { name: "クミン", qty: 0.5, unit: "小さじ" },
      { name: "ご飯", qty: 200, unit: "g" },
      { name: "ピザ用チーズ", qty: 25, unit: "g" },
      { name: "レタス", qty: 1, unit: "枚" },
    ],
    fixed: [
      { name: "塩・味塩コショウ", text: "適量" },
      { name: "鷹の爪", text: "適量" },
      { name: "乾燥パセリ", text: "適量" },
    ],
    steps: [
      "サラダ油でにんにく・玉ねぎ（60g分）・鷹の爪を炒める。",
      "ホールトマト・コンソメ・塩を加えて炒め、つぶしてソース状にする。",
      "別で塩コショウした豚ひき肉を炒める。",
      "にんにく・玉ねぎ（30g分）を加えて炒める。",
      "ケチャップ・ウスターソース・コンソメ・チリパウダー・オレガノ・クミンを加えて炒める。",
      "ご飯にレタスを敷き、トマトソースと肉をのせる。",
      "ピザ用チーズ・パセリをのせて完成。",
    ],
  },

  // ================= 副菜 =================
  {
    id: "mugen-piman",
    title: "丸ごと無限ピーマン",
    type: "side",
    ingredientTags: ["ピーマン"],
    time: "約8分（レンジ加熱のみ）",
    genre: "中華風・レンジ調理",
    blurb: "ピーマンを丸ごとレンジでチンして和えるだけ。コンロを塞がず火も使わない副菜。",
    url: "https://bazurecipe.com/2020/05/05/%E4%B8%B8%E3%81%94%E3%81%A8%E7%84%A1%E9%99%90%E3%83%94%E3%83%BC%E3%83%9E%E3%83%B3/",
    baseServings: 2,
    ing: [
      { name: "ピーマン", qty: 4, unit: "個" },
      { name: "ツナ缶", qty: 0.5, unit: "缶" },
      { name: "ごま油", qty: 2, unit: "小さじ" },
    ],
    fixed: [
      { name: "塩", text: "適量（3つまみ目安）" },
      { name: "味の素", text: "適量（お好みで）" },
      { name: "コショウ", text: "少々" },
    ],
    steps: [
      "ピーマンを容器に入れてラップする。",
      "600Wの電子レンジで4分加熱する。",
      "ツナ缶の油を切り、半量を用意する。",
      "加熱したピーマンにツナ・塩・味の素・コショウ・ごま油を加えて和える。",
    ],
  },
  {
    id: "shiko-moyashi-namul",
    title: "至高のもやしナムル",
    type: "side",
    ingredientTags: ["もやし"],
    time: "約10分",
    genre: "中華・韓国風・濃い味",
    blurb: "1袋数十円のもやしが主役。ナンプラーでうま味たっぷり。コスパ最強の副菜。",
    url: "https://bazurecipe.com/2022/01/04/%E8%87%B3%E9%AB%98%E3%81%AE%E3%82%82%E3%82%84%E3%81%97%E3%83%8A%E3%83%A0%E3%83%AB/",
    baseServings: 2,
    ing: [
      { name: "もやし", qty: 200, unit: "g" },
      { name: "塩", qty: 0.33, unit: "小さじ" },
      { name: "砂糖", qty: 0.33, unit: "小さじ" },
      { name: "ナンプラー", qty: 0.33, unit: "小さじ" },
      { name: "ごま油", qty: 2, unit: "小さじ" },
    ],
    fixed: [
      { name: "味の素", text: "適量（お好みで）" },
      { name: "いりゴマ", text: "適量" },
      { name: "ラー油", text: "お好みで" },
    ],
    steps: [
      "もやしをレンジ加熱、または熱湯でサッと茹でて水気を切る。",
      "塩・砂糖・ナンプラー・味の素・ごま油を加えて和える。",
      "いりゴマ・お好みでラー油をかけて完成。",
    ],
  },
  {
    id: "endless-moyashi",
    title: "エンドレスもやし炒め",
    type: "side",
    ingredientTags: ["もやし"],
    time: "約10分",
    genre: "洋風・ガーリックバター",
    blurb: "もやし＋ベーコンをバター醤油で炒めるだけ。安いのに無限に食える濃い味副菜。",
    url: "https://bazurecipe.com/2024/01/18/%E3%82%A8%E3%83%B3%E3%83%89%E3%83%AC%E3%82%B9%E3%82%82%E3%82%84%E3%81%97/",
    baseServings: 2,
    ing: [
      { name: "もやし", qty: 200, unit: "g" },
      { name: "にんにく", qty: 10, unit: "g" },
      { name: "ベーコン", qty: 40, unit: "g" },
      { name: "バター", qty: 10, unit: "g" },
      { name: "オリーブオイル", qty: 1, unit: "小さじ" },
      { name: "醤油", qty: 1, unit: "大さじ" },
      { name: "砂糖", qty: 0.5, unit: "小さじ" },
    ],
    fixed: [
      { name: "味の素", text: "適量（お好みで）" },
      { name: "黒コショウ", text: "適量" },
    ],
    steps: [
      "オリーブオイルでにんにくを炒めて取り出す。",
      "ベーコンを炒める。",
      "もやしを加えて炒める。",
      "砂糖・醤油・味の素・バターを入れて炒める。",
      "黒胡椒をふり、ガーリックチップをのせて完成。",
    ],
  },
  {
    id: "shin-mugen-cabbage",
    title: "シン・無限キャベツ",
    type: "side",
    ingredientTags: ["キャベツ"],
    time: "約15分（塩もみ10分を含む）",
    genre: "洋風・ガーリックマヨ",
    blurb: "キャベツ1/4玉がペロリ。マヨ×にんにく×鰹節の濃厚うま味で箸が止まらない。",
    url: "https://bazurecipe.com/2023/04/25/%E3%82%B7%E3%83%B3%EF%BD%A5%E7%84%A1%E9%99%90%E3%82%AD%E3%83%A3%E3%83%99%E3%83%84/",
    baseServings: 2,
    ing: [
      { name: "キャベツ", qty: 250, unit: "g" },
      { name: "ベーコン", qty: 40, unit: "g" },
      { name: "マヨネーズ", qty: 2, unit: "大さじ" },
      { name: "すりごま", qty: 2, unit: "小さじ" },
      { name: "にんにく", qty: 0.5, unit: "片" },
      { name: "鰹節", qty: 2, unit: "g" },
      { name: "塩", qty: 0.5, unit: "小さじ" },
    ],
    fixed: [
      { name: "味の素", text: "適量（お好みで）" },
      { name: "黒コショウ", text: "適量" },
    ],
    steps: [
      "キャベツを千切りにし、塩をもみ込んで10分置く。",
      "キャベツをよく絞って水分を切る。",
      "ベーコンを焼く。",
      "キャベツ・ベーコン・マヨネーズ・鰹節・味の素・すりごま・黒胡椒・おろしにんにくを混ぜる。",
      "味見をして、必要なら塩で調える。",
    ],
  },
];

// 素材チップ（この順で表示）
const INGREDIENTS = [
  { key: "豚こま", label: "豚こま肉", type: "main" },
  { key: "鶏もも", label: "鶏もも肉", type: "main" },
  { key: "鶏むね", label: "鶏むね肉", type: "main" },
  { key: "ひき肉", label: "ひき肉", type: "main" },
  { key: "ピーマン", label: "ピーマン", type: "side" },
  { key: "もやし", label: "もやし", type: "side" },
  { key: "キャベツ", label: "キャベツ", type: "side" },
];
